config/routes.rb
Rails.application.routes.draw do
  post 'orders/confirm' => 'orders#confirm'
  post 'orders/thanks' => 'orders#thanks'
  post 'contacts/confirm' => 'contacts#confirm'
  post 'contacts/thanks' => 'contacts#thanks'

  root to: "home#show"
  resource :gallery, only: :show
  resource :price, only: :show
  resource :link , only: :show
  resource :order, only: [:new, :create]
  resource :contact, only: [:new, :create]
  resource :qa, only: :show
  resource :about, only: :show

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name_kana, presence: true, length: { maximum: 50 }
  validates :first_name_kana, presence: true, length: { maximum: 50 }
  enum size: %i(A5 A4 A3 A2 A1 other)
end

app/models/price.rb
class Price < ActiveRecord::Base
  validates :size, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :purpose, presence: true
end

app/controllers/_orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end

  def create
  end
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def show
  end
end

app/controllers/orders_controller.rb
require 'date'
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end

  def confirm
    @order = Order.new(order_params)
    unless @order.purpose == 'other'
      @order.other_purpose = ""
    end
  end

  def thanks
    @order = Order.new(order_params)
    @order.save!
    InquiryMailer.order_email_to_customer(@order).deliver
    InquiryMailer.order_email_to_owner(@order).deliver
    render action: :thanks
  end

  private

    def order_params
      params.require(:order).permit(:last_name, :first_name,
                                    :last_name_kana, :first_name_kana,
                                    :mail, :phone_number, :cellphone_number,
                                    :residence, :mailing_address,
                                    :residence_zip_code, :mailing_zip_code,
                                    :receipt_enabled, :receipt_address, :receipt_proviso,
                                    :purpose, :other_purpose, :preffered_date,
                                    :size, :length, :width,
                                    :remarks
                                   )
    end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  def show
    @price = Price.all
  end
end

app/controllers/qas_controller.rb
class QasController < ApplicationController
  def show
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/qas_helper.rb
module QasHelper
end

app/views/layouts/_footer.html.haml
#footer
  .footer_content
    = image_tag('logo.jpg', class:"logo", height: "50px")
    = link_to image_tag("facebook.png", class: "facebook_button pull-right", height: "20px"), "https://ja-jp.facebook.com/cocomugen"
    .copyright
      Copyright @ CoCoからInfinity All rights reserved.

app/views/layouts/_header.html.haml
%header
  %nav.navbar.navbar-fixed-top.navbar-default
    .container-fluid
      -# .row
      -#   .col-xs-3
      -#   .col-xs-9
      .navbar-header
        %button.navbar-toggle{ type: "button",
                               "data-toggle" => "collapse",
                               "data-target" => "#navbarmenu" }
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{ href: root_path, target:"_blank"} CoCoからInfinity
        -# %a.navbar-brand= link_to 'CoCoから～Infinity～', root_path
      .navbar-collapse.collapse#navbarmenu
        %ul.nav.navbar-nav
          %li= link_to 'About', about_path, target:["_blank"]
          %li= link_to 'Gallery', gallery_path, target:["_blank"]
          %li= link_to 'Price', price_path, target:["_blank"]
          %li= link_to 'Order',new_order_path, target:["_blank"]
          %li= link_to 'Contact',new_contact_path, target:["_blank"]
          %li= link_to 'Q&A', qa_path, target:["_blank"]
        %ul.nav.navbar-nav.navbar-right
          %li= link_to image_tag("facebook.png", class: "facebook_button", height: "20px"), "https://ja-jp.facebook.com/cocomugen"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title CocoMugen
    %meta{ charset: "utf-8"}
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-59479182-1', 'auto');
      ga('send', 'pageview');
    = favicon_link_tag
  %body
    #wrapper
      -# %nav.navbar.navbar-default.navbar-fixed-top
      -#   .container
      -#     .navbar-header
      -#       %a.navbar-brand{ href: "#" } header
      -#     %ul.nav.navbar-nav
      -#       %li.active= link_to 'link1', '#'
      -#       %li= link_to 'link2', '#'
      = render 'layouts/header'
      .container-fluid
        = yield
      #push
    = render 'layouts/footer'